### ISSUE TITLE
IAudioClient::Initialize caused an error: 0x88890008 how to fix

### ISSUE THREAD

**Issue by thanosdummythicc** [DarthAffe/KeyboardAudioVisualizer#85]
[14/01/2021 15:32:34] Exception!

Message:
IAudioClient::Initialize caused an error: 0x88890008, "Unknown HRESULT".

StackTrace:
   at CSCore.SoundIn.WasapiCapture.InitializeInternal()
   at CSCore.SoundIn.WasapiCapture.Initialize()
   at KeyboardAudioVisualizer.AudioCapture.CSCoreAudioInput.Initialize()
   at KeyboardAudioVisualizer.AudioProcessing.AudioVisualizationFactory.InitializeInstance()
   at KeyboardAudioVisualizer.AudioProcessing.AudioVisualizationFactory.Initialize()
   at KeyboardAudioVisualizer.App.OnStartup(StartupEventArgs e)

**Comment by DarthAffe** [comment]
Hey, this was already discussed in https://github.com/DarthAffe/KeyboardAudioVisualizer/issues/27
